<a href="https://colab.research.google.com/github/owaisahmad315/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Load in numpy (remember to pip install numpy first)**

In [114]:
!pip install numpy

In [115]:
import numpy as np

#**The Basics**

In [116]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [117]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [118]:
# Get dimension
a.ndim

1

In [119]:
b.ndim

2

In [120]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [121]:
# Get type
a.dtype

dtype('int64')

In [122]:
# Get size
a.itemsize


8

**Accessing/Changing specific elements, rows, columns, etc**

In [123]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [124]:
# Get a specific Element
# rows and columns are [rows, columns]
a[1,5]

13

In [125]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [126]:
# Get a specific column
a[: , 0]

array([1, 8])

In [127]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [128]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [129]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [130]:
# Get specific column work outside in
b[0,1,1]

4

In [131]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


#Initializing different types of arrays

In [132]:
# All zero's matrix
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [133]:
# All ones
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [134]:
# Any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [135]:
# Any other numbers (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [136]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [137]:
# Random Decimal number
np.random.rand(4,2)

array([[0.60626093, 0.11414324],
       [0.81201382, 0.34336812],
       [0.79534557, 0.20996567],
       [0.91783089, 0.81404781]])

In [138]:
# Random Integer
np.random.randint(7)

0

In [139]:
np.random.randint(-4,8, size=(3,3))

array([[ 6,  6, -4],
       [ 0,  3, -4],
       [-4,  1,  4]])

In [140]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [141]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [142]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [143]:
# Be carefull when copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("this is b: ", b)
print(a)

this is b:  [100   2   3]
[1 2 3]


#**Mathematics**

In [144]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [145]:
a +2

array([3, 4, 5, 6])

In [146]:
a-2

array([-1,  0,  1,  2])

In [147]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [148]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [149]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#**Linear Algebra**

In [150]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [151]:
# Find the determinent
c = np.identity(3)
np.linalg.det(c)

1.0

#**Statistics**

In [152]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [153]:
np.min(stats)

1

In [154]:
np.max(stats)

6

#**Reorganizing Arrays**

In [177]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((1,8))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4 5 6 7 8]]


In [156]:
# Vertically stacking vertors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v2,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [5, 6, 7, 8],
       [5, 6, 7, 8]])

In [157]:
# Horizontol stacking
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h2,h1))

array([[0., 0., 1., 1., 1., 1.],
       [0., 0., 1., 1., 1., 1.]])

#**Loading Data From File**

In [161]:
from google.colab import files

# Upload a file from your local machine
uploaded = files.upload()

# Read the content of the uploaded file
file_content = list(uploaded.values())[0]


Saving data.txt.txt to data.txt.txt


In [163]:
np.genfromtxt('data.txt', delimiter = ',')


array([[  1.,  13.,  21.,  11., 196.,  75.,   4.,   3.,  34.,   6.,   7.,
          8.,   0.,   1.,   2.,   3.,   4.,   5.],
       [  3.,  42.,  12.,  33., 766.,  75.,   4.,  55.,   6.,   4.,   3.,
          4.,   5.,   6.,   7.,   0.,  11.,  12.],
       [  1.,  22.,  33.,  11., 999.,  11.,   2.,   1.,  78.,   0.,   1.,
          2.,   9.,   8.,   7.,   1.,  76.,  88.]])

#**Boolean Masking and Advance Indexing**

In [166]:
import pandas as pd
filedata = pd.read_csv('data.txt')


In [170]:
filedata > 50

1     13     21     11   196     75      4      3     34      6      7  \
0  False  False  False  False  True   True  False   True  False  False  False   
1  False  False  False  False  True  False  False  False   True  False  False   

       8      0    1.1      2    3.1    4.1      5  
0  False  False  False  False  False  False  False  
1  False  False  False  False  False   True   True

In [172]:
filedata[filedata > 50]

1  13  21  11  196    75   4     3    34   6   7   8   0  1.1   2  3.1  \
0 NaN NaN NaN NaN  766  75.0 NaN  55.0   NaN NaN NaN NaN NaN  NaN NaN  NaN   
1 NaN NaN NaN NaN  999   NaN NaN   NaN  78.0 NaN NaN NaN NaN  NaN NaN  NaN   

    4.1     5  
0   NaN   NaN  
1  76.0  88.0

In [173]:
# You can index with list in Numpy
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,3]]

array([2, 3, 4])