<a href="https://colab.research.google.com/github/owaisahmad315/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Load in numpy (remember to pip install numpy first)**

In [47]:
!pip install numpy

In [48]:
import numpy as np

#**The Basics**

In [49]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [50]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [51]:
# Get dimension
a.ndim

1

In [52]:
b.ndim

2

In [53]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [54]:
# Get type
a.dtype

dtype('int64')

In [55]:
# Get size
a.itemsize


8

**Accessing/Changing specific elements, rows, columns, etc**

In [56]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [57]:
# Get a specific Element
# rows and columns are [rows, columns]
a[1,5]

13

In [58]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [59]:
# Get a specific column
a[: , 0]

array([1, 8])

In [60]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [61]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [62]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [63]:
# Get specific column work outside in
b[0,1,1]

4

In [64]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


#Initializing different types of arrays

In [65]:
# All zero's matrix
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [66]:
# All ones
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [67]:
# Any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [68]:
# Any other numbers (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
# Random Decimal number
np.random.rand(4,2)

array([[0.92611127, 0.73861372],
       [0.77355384, 0.55025474],
       [0.37388268, 0.30261424],
       [0.31137931, 0.57393401]])

In [71]:
# Random Integer
np.random.randint(7)

0

In [72]:
np.random.randint(-4,8, size=(3,3))

array([[ 5, -4,  0],
       [ 3,  1,  4],
       [ 0, -2, -4]])

In [73]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [74]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [75]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [80]:
# Be carefull when copying arrays
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print("this is b: ", b)
print(a)

this is b:  [100   2   3]
[1 2 3]


#**Mathematics**

In [81]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [82]:
a +2

array([3, 4, 5, 6])

In [83]:
a-2

array([-1,  0,  1,  2])

In [84]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [85]:
# take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [86]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])