<a href="https://colab.research.google.com/github/owaisahmad315/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Load in numpy (remember to pip install numpy first)**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np



#**The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [ ]:
!apt-get install -y git


Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.


In [43]:
!git config --global user.email "owaisahmad014@gmail.com"
!git config --global user.name "Owais Ahmad"


In [ ]:
!git clone https://github.com/owaisahmad315/NumPy.git


Cloning into 'NumPy'...


In [19]:
! git add .

In [20]:
! git status

On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   Lecture_27.ipynb
	new file:   Lecture_34.ipynb
	new file:   Lecture_35.ipynb
	new file:   NumPy.ipynb
	new file:   Untitled



In [23]:
! git commit -a -m "firstt commit"

[master 229fd5c] firstt commit
 5 files changed, 5 insertions(+), 1 deletion(-)
 rewrite Lecture_27.ipynb (98%)
 create mode 100644 Lecture_34.ipynb
 create mode 100644 Lecture_35.ipynb
 create mode 100644 NumPy.ipynb
 create mode 100644 Untitled


In [25]:
username = input("username")

usernameowaisahmad315


In [26]:
from getpass import getpass
password = getpass("enter password")

enter password··········


In [37]:
!git remote rm origin

In [38]:
!git remote add origin https://github.com/owaisahmad315/NumPy.git

In [48]:
! git push origin main

fatal: could not read Username for 'https://github.com': No such device or address


In [50]:
!apt-get update
!apt-get install git
!git config --global credential.helper manager


Get:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease [3,626 B]
Hit:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:3 http://archive.ubuntu.com/ubuntu jammy InRelease
Get:4 http://security.ubuntu.com/ubuntu jammy-security InRelease [110 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease [119 kB]
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Get:9 http://security.ubuntu.com/ubuntu jammy-security/universe amd64 Packages [1,047 kB]
Hit:10 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:11 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Get:12 http://security.ubuntu.com/ubuntu jammy-security/restricted amd64 Packages [1,582 kB]
Get:13 http://archive.ubuntu.com/ubuntu jammy-updates

In [51]:
!echo "# NumPy" >> README.md
!git init
!git add README.md
!git commit -m "first commit"
!git branch -M main
!git remote add origin https://github.com/owaisahmad315/NumPy.git
!git push -u origin main

Reinitialized existing Git repository in /content/drive/MyDrive/Colab Notebooks/.git/
[main 266d8e0] first commit
 1 file changed, 1 insertion(+)
error: remote origin already exists.
git: 'credential-manager' is not a git command. See 'git --help'.
fatal: could not read Username for 'https://github.com': No such device or address


In [53]:
!apt-get update
!apt-get install git
!apt-get install libsecret-1-0 libsecret-1-dev
!git config --global credential.helper /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret



Hit:1 https://cloud.r-project.org/bin/linux/ubuntu jammy-cran40/ InRelease
Hit:2 http://security.ubuntu.com/ubuntu jammy-security InRelease
Hit:3 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64  InRelease
Hit:4 http://archive.ubuntu.com/ubuntu jammy InRelease
Hit:5 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Hit:6 http://archive.ubuntu.com/ubuntu jammy-backports InRelease
Hit:7 https://ppa.launchpadcontent.net/c2d4u.team/c2d4u4.0+/ubuntu jammy InRelease
Hit:8 https://ppa.launchpadcontent.net/deadsnakes/ppa/ubuntu jammy InRelease
Hit:9 https://ppa.launchpadcontent.net/graphics-drivers/ppa/ubuntu jammy InRelease
Hit:10 https://ppa.launchpadcontent.net/ubuntugis/ppa/ubuntu jammy InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
git is already the newest version (1:2.34.1-1ubuntu1.10).
0 upgraded, 0 newly installed, 0 to remove and 24 not upgraded.
Reading package 

In [72]:
!git rm /content/drive/MyDrive/Colab\ Notebooks/python_7th semester.ipynb

fatal: pathspec '/content/drive/MyDrive/Colab Notebooks/python_7th' did not match any files


In [64]:
!git commit -m "Remove unwanted files"


[main 6c432d0] Remove unwanted files
 5 files changed, 5 deletions(-)
 delete mode 100644 Lecture_23.ipynb
 delete mode 100644 Lecture_25.ipynb
 delete mode 100644 Lecture_27.ipynb
 delete mode 100644 Lecture_34.ipynb
 delete mode 100644 Lecture_35.ipynb


In [65]:
!git push origin main


/usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret store: 1: /usr/share/doc/git/contrib/credential/libsecret/git-credential-libsecret: not found
Enumerating objects: 3, done.
Counting objects: 100% (3/3), done.
Delta compression using up to 2 threads
Compressing objects: 100% (2/2), done.
Writing objects: 100% (2/2), 236 bytes | 78.00 KiB/s, done.
Total 2 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/owaisahmad315/NumPy.git
   c490a0d..6c432d0  main -> main
