<a href="https://colab.research.google.com/github/owaisahmad315/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Load in numpy (remember to pip install numpy first)**

In [ ]:
!pip install numpy

In [ ]:
import numpy as np



#**The Basics**

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [ ]:
# Get dimension
a.ndim

1

In [ ]:
b.ndim

2

In [ ]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [ ]:
# Get type
a.dtype

dtype('int64')

In [ ]:
# Get size
a.itemsize


8

**Accessing/Changing specific elements, rows, columns, etc**

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Get a specific Element
# rows and columns are [rows, columns]
a[1,5]

13

In [ ]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [ ]:
# Get a specific column
a[: , 0]

array([1, 8])

In [ ]:
# getting a little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [ ]:
a[1,5] = 20
a[:,2] = [1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
# Get specific column work outside in
b[0,1,1]

4

In [ ]:
# Replace
b[:,1,:] = [[9,9],[8,8]]
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


#Initializing different types of arrays

In [ ]:
# All zero's matrix
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [ ]:
# All ones
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other numbers
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [ ]:
# Any other numbers (full_like)
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])