<a href="https://colab.research.google.com/github/owaisahmad315/NumPy/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Load in numpy (remember to pip install numpy first)**

In [3]:
!pip install numpy

In [4]:
import numpy as np



#**The Basics**

In [5]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [6]:
b = np.array([[9.0,8.0,7.0], [6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [7]:
# Get dimension
a.ndim

1

In [8]:
b.ndim

2

In [9]:
# Get shape
print("The shape of a is : ", a.shape)
print("The shape of b is : ", b.shape)


The shape of a is :  (3,)
The shape of b is :  (2, 3)


In [10]:
# Get type
a.dtype

dtype('int64')

In [13]:
!git init
!git add NumPy.ipynb

hint: Using 'master' as the name for the initial branch. This default branch name
hint: is subject to change. To configure the initial branch name to use in all
hint: of your new repositories, which will suppress this warning, call:
hint: 
hint: 	git config --global init.defaultBranch <name>
hint: 
hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
hint: 'development'. The just-created branch can be renamed via this command:
hint: 
hint: 	git branch -m <name>
Initialized empty Git repository in /content/.git/
fatal: pathspec 'NumPy.ipynb' did not match any files


In [11]:
! git commit -a -m "firstt commit"

fatal: not a git repository (or any of the parent directories): .git


In [12]:
!git push origin main


fatal: not a git repository (or any of the parent directories): .git
